[package]
name = "layer7waf-geoip"
version = "0.1.0"
edition = "2021"

[dependencies]
layer7waf-common = { workspace = true }
maxminddb = { workspace = true }
arc-swap = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
