[package]
name = "layer7waf-coraza"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
layer7waf-common = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
