[package]
name = "layer7waf-rate-limit"
version = "0.1.0"
edition = "2021"

[dependencies]
layer7waf-common = { workspace = true }
dashmap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
